# SITE CONFIGURATION
title: Web dizajn koji donosi rezultate. # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Mi dizajniramo i izrađujemo lijepe web stranice koje rade za vas,
  vaše posjetitelje i vaše poslovanje. I to je ono što je doista važno.
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Mareno
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Mi dizajniramo i izrađujemo lijepe web stranice koje rade za vas, vaše posjetitelje i vaše poslovanje. I to je ono što je doista važno.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: mail@marenodizajn.com # email for form submission

twitter_username: mareno.dizajn # replace with your_twitter_username or comment to remove link from footer
github_username:  mareno # replace with your_github_username or comment to remove link from footer
instagram_username: mareno.dizajn # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
